SET 'auto.offset.reset'='earliest';

-- We have a CSV file with the order lines which we publish using SpoolDir
-- This is the raw data
CREATE STREAM orders_raw WITH (KAFKA_TOPIC='orders_raw', VALUE_FORMAT='AVRO');

-- Now use KSQL to parse out the equivalent third normal form tables (this is equivalent to 
-- CDC coming from the DWH)
CREATE STREAM ORDERS_3NF WITH (VALUE_FORMAT='AVRO', TIMESTAMP='ORDERDATE', timestamp_format='M/d/yyyy h:mm') AS 
  SELECT ORDERNUMBER, ORDERDATE, STATUS, QTR_ID, MONTH_ID, YEAR_ID, DEALSIZE, CUSTOMERNAME 
  FROM orders_raw PARTITION BY ORDERNUMBER;
  
CREATE TABLE T_ORDERS_3NF WITH (KAFKA_TOPIC='ORDERS_3NF', VALUE_FORMAT='AVRO', KEY='ORDERNUMBER');

CREATE STREAM ORDERLINES_3NF WITH (VALUE_FORMAT='AVRO') AS 
  SELECT ORDERNUMBER, ORDERLINENUMBER, QUANTITYORDERED, PRICEEACH, PRODUCTCODE FROM orders_raw;

CREATE STREAM CUSTOMERS_3NF WITH (VALUE_FORMAT='AVRO') AS 
  SELECT CUSTOMERNAME, PHONE, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, CONTACTLASTNAME, CONTACTFIRSTNAME 
  FROM orders_raw PARTITION BY CUSTOMERNAME;

CREATE TABLE T_CUSTOMERS_3NF WITH (KAFKA_TOPIC='CUSTOMERS_3NF', VALUE_FORMAT='AVRO', KEY='CUSTOMERNAME');

CREATE STREAM PRODUCTS_3NF WITH (VALUE_FORMAT='AVRO') AS 
  SELECT PRODUCTCODE,  PRODUCTLINE, MSRP 
  FROM orders_raw PARTITION BY PRODUCTCODE;

CREATE TABLE T_PRODUCTS_3NF WITH (KAFKA_TOPIC='PRODUCTS_3NF', VALUE_FORMAT='AVRO', KEY='PRODUCTCODE');

CREATE STREAM COUNTRIES_3NF WITH (VALUE_FORMAT='AVRO') AS 
  SELECT COUNTRY, TERRITORY 
  FROM orders_raw PARTITION BY COUNTRY;

CREATE TABLE T_COUNTRIES_3NF WITH (KAFKA_TOPIC='COUNTRIES_3NF', VALUE_FORMAT='AVRO', KEY='COUNTRY');
