create table ORDERS (
	 ORDERNUMBER INT PRIMARY KEY,
	 ORDERDATE timestamp DEFAULT CURRENT_TIMESTAMP, 
	 STATUS VARCHAR(50), 
	 QTR_ID INT, 
	 MONTH_ID INT, 
	 YEAR_ID INT, 
	 DEALSIZE NUMERIC, 
	 CUSTOMERNAME VARCHAR(50)
);

create table ORDERLINES (
	ORDERNUMBER INT, 
	ORDERLINENUMBER INT, 
	QUANTITYORDERED INT, 
	PRICEEACH NUMERIC, 
	PRODUCTCODE VARCHAR(50)
);

create table CUSTOMERS (
	CUSTOMERNAME VARCHAR(50), 
	PHONE VARCHAR(13), 
	ADDRESSLINE1 VARCHAR(50), 
	ADDRESSLINE2 VARCHAR(50), 
	CITY VARCHAR(50), 
	STATE VARCHAR(50), 
	POSTALCODE VARCHAR(50), 
	COUNTRY VARCHAR(50), 
	CONTACTLASTNAME VARCHAR(50), 
	CONTACTFIRSTNAME VARCHAR(50)
);

create table PRODUCTS (
	PRODUCTCODE VARCHAR(50),  
	PRODUCTLINE VARCHAR(50), 
	MSRP NUMERIC
);

create table COUNTRIES (
	COUNTRY VARCHAR(50), 
	TERRITORY VARCHAR(50)
);


